name: Auto Update ASN

on:
  push:
    branches: [ "main" ]
  schedule:
    - cron:  '0 9 * * *'

permissions:
  contents: write

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4.1.2
    - name: Set up Python
      uses: actions/setup-python@v5.0.0
      with:
        python-version: "3.10"
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install requests bs4
    - name: TimezoneAction
      uses: MathRobin/timezone-action@v1.1
      with:
        timezoneLinux: 'America/New_York'
    - name: Run .py Files
      run: |
        python CNASN.py
        python USASN.py
    - name: Git Auto Commit
      uses: stefanzweifel/git-auto-commit-action@v5.0.0
      with:
        commit_message: Update ASN
